name: usagi_quest
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/drawerIcon.png
    - assets/p0.png
    - assets/p1_1.png
    - assets/p1_2.png
    - assets/p2.png
    - assets/p3_1.png
    - assets/p3_2.png
    - assets/p4.png
    - assets/p5_1.png
    - assets/p5_2.png
    - assets/p6.png
    - assets/p7.png

    - assets/p9_1.png
    - assets/p9_2.png
    - assets/p10.png
    - assets/p11_1_1.png
    - assets/p11_1_2.png
    - assets/p11_2_1.png
    - assets/p11_2_2.png
    - assets/p11_3_1.png
    - assets/p11_3_2.png
    - assets/p11_4_1.png
    - assets/p11_4_2.png
    - assets/p13.png
    - assets/p14.png

    - assets/solution_1.png
    - assets/solution_2.png
    - assets/solution_3.png